pull_request_rules:
  # Automatic Merging (humans)
  - name: automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
    actions:
      merge:
        method: merge
        strict: smart

  - name: automatic merge without review
    conditions:
      - author=thislooksfun
      - base=master
    actions:
      merge:
        method: merge
        strict: smart

  # Automatic Merging (bots)
  # These are awaiting #71
  # - name: automatic merge from greenkeeper
  #   conditions:
  #     - author=greenkeeper[bot]
  #     - status-success=greenkeeper/verify
  #     - base=master
  #   actions:
  #     merge:
  #       method: merge
  #       strict: smart
  #
  # - name: automatic merge from dependabot
  #   conditions:
  #     - author~=^dependabot(|-preview)\[bot\]$
  #     - base=master
  #   actions:
  #     merge:
  #       method: merge
  #       strict: smart

  # Quality of life
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

  - name: Remove outdated reviews
    conditions: []
    actions:
      dismiss_reviews: {}

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict :(
