pull_request_rules:
  # Automatic Merging (humans)
  - name: "Automatic merge for my changes to master when tagged"
    conditions:
      # Tagged ready
      - label=ready-to-merge
      # On master branch
      - base=master
    actions:
      merge:
        method: merge
        strict: true

  # This is awaiting #71
  # # Automatic Merging (bots)
  # - name: "Automatic merge for Greenkeeper pull requests"
  #   conditions:
  #     # Was sent from Greenkeeper
  #     - author=greenkeeper[bot]
  #     - status-success=greenkeeper/verify
  #     # On master branch
  #     - base=master
  #   actions:
  #     merge:
  #       method: merge
  #       strict: true

  # Quality of life
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

  - name: Remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}

  - name: Assign me
    conditions:
      - -author=greenkeeper[bot]
      - -author=thislooksfun
      - base=master
    actions:
      assign:
        users:
          - thislooksfun
