pull_request_rules:
  # Automatic Merging (humans)
  - name: automatic merge without review
    conditions:
      # By me
      - author=thislooksfun
      # Tagged ready
      - label=ready-to-merge
      # On master branch
      - base=master
    actions:
      merge:
        method: merge
        strict: smart

  # Automatic Merging (humans)
  - name: automatic merge
    conditions:
      # At least one review
      - "#approved-reviews-by>=1"
      # Tagged ready
      - label=ready-to-merge
      # On master branch
      - base=master
    actions:
      merge:
        method: merge
        strict: smart

  # Automatic Merging (bots)
  # These are awaiting #71
  # - name: automatic merge from greenkeeper
  #   conditions:
  #     # Was sent from Greenkeeper
  #     - author=greenkeeper[bot]
  #     - status-success=greenkeeper/verify
  #     # On master branch
  #     - base=master
  #   actions:
  #     merge:
  #       method: merge
  #       strict: smart
  #
  # - name: automatic merge from dependabot
  #   conditions:
  #     # Was sent from dependabot
  #     - author~=^dependabot(|-preview)\[bot\]$
  #     # On master branch
  #     - base=master
  #   actions:
  #     merge:
  #       method: merge
  #       strict: smart

  # Quality of life
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

  - name: Remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}

  - name: Assign me
    conditions:
      - -author=greenkeeper[bot]
      - -author=thislooksfun
      - base=master
    actions:
      assign:
        users:
          - thislooksfun
