name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      # The --slient suppresses any npm ELIFECYCLE errors, but does not silence
      # script output.
      - run: npm run test:unit:cover --silent
        env:
          CI: true
      - name: Codecov
        run: npm run upload_coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Snyk
        run: npm run snyk_monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
